In [2]:
import numpy as np
#여기서는 설명을 위해 import하지만 자주 쓰이는 import문은 startup파일에 써놓는 것이 좋다.

In [4]:
#1차원 배열(vector)
array=np.array([0,1,2,3,4,5])
print(array)

[0 1 2 3 4 5]


In [6]:
#2차원 배열(3*1 matrix)
array=np.array([[0],[1],[2]])
print(array)

[[0]
 [1]
 [2]]


In [8]:
#3차원 배열(2*3*4 matrix)
array=np.array([
    [[0,1,2,3],
    [1,2,3,4],
    [2,3,4,5]],
    [[1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]]
])
print(array)
print(array.ndim,array.shape)

[[[0 1 2 3]
  [1 2 3 4]
  [2 3 4 5]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]]
3 (2, 3, 4)


In [9]:
na=np.array([1,2,3,4,5,6,7,8])
na

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
na.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
rna=np.reshape(na,(4,2))
rna
#same outcome with above

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
rna.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [14]:
array

array([[[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]]])

In [16]:
#indexing
print(array[1][1][2])
print(array[1,1,2])

4
4


In [17]:
#offsetting
result=array[1:,1:,2:]
print(result)
print(result.ndim,result.shape)

[[[4 5]
  [5 6]]]
3 (1, 2, 2)


In [18]:
result[0].ndim

2

In [21]:
#making zero matrix with int datatype natation
data=np.zeros(5,dtype=int)
data

array([0, 0, 0, 0, 0])

In [23]:
#change value by indexing
data[1]=1
data

array([0, 1, 0, 0, 0])

In [25]:
data[:3]=2
data

array([2, 2, 2, 0, 0])

In [26]:
z=np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
z[1:,2:]=2 #slicing이나 indexing을 할때 [depth,row,column]순이다.
z

array([[0., 0., 0., 0.],
       [0., 0., 2., 2.],
       [0., 0., 2., 2.]])

### zeros
- 행렬을 만들고 안에 0으로 채워 넣는다.

In [29]:
#1차원
#dtype으로 데이터 타입을 설정할 수 있다. default = float
z=np.zeros(5,dtype=int)
print(z)
print(z.ndim,z.shape)

[0 0 0 0 0]
1 (5,)


In [30]:
#2차원
z=np.zeros((2,3))
print(z)
print(z.ndim,z.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
2 (2, 3)


In [31]:
#3차원(2*3*4)
z=np.zeros((2,3,4))
print(z)
print(z.ndim,z.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3 (2, 3, 4)


### ones
- 행렬을 만들고 안에 1을 채워 넣는다.

In [32]:
#3차원(2*3*4)
one_na=np.ones((2,3,4,))
print(one_na)
print(one_na.ndim,one_na.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4)


### eye
- 단위 행렬 데이터를 만든다.

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### like
- 행렬 안에 있는 모든 데이터를 0이나 1로 바꿀 수 있다.

In [34]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [35]:
ls=np.ones_like(z)
print(ls)
print(ls.ndim,ls.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4)


In [36]:
one_na

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [37]:
ls=np.zeros_like(one_na)
print(ls)
print(ls.ndim,ls.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3 (2, 3, 4)


### empty
- 빈행렬을 만든다.
- 실제로는 빈데이터가 아니라 더미 데이터가 들어간다.

In [38]:
a=np.empty((5,5))
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### arange
- range와 기능이 같다.
- 하지만 큰데이터에서 range보다 속도가 더 빠르다.

In [39]:
#range와 arange의 속도 비교
size=int(1E6)#10**6
%timeit for x in range(size):x**2
%timeit for x in np.arange(size):x**2    

294 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
172 ms ± 299 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### linspace,logspace

In [40]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

In [41]:
print(np.logspace(2,4,3))
print(np.logspace(2,3,3))

[  100.  1000. 10000.]
[ 100.          316.22776602 1000.        ]


### random
- seed
- rand(uniform)
- randn(gaussian)
- randint
- shuffle
- choice

In [42]:
np.random.seed(0)
rd=np.random.rand(10)
rdn=np.random.randn(10)
print(rd)
print(rdn)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323  0.33367433
  1.49407907 -0.20515826  0.3130677  -0.85409574]


In [43]:
r=np.random.rand(2,3,4)
r

array([[[0.14335329, 0.94466892, 0.52184832, 0.41466194],
        [0.26455561, 0.77423369, 0.45615033, 0.56843395],
        [0.0187898 , 0.6176355 , 0.61209572, 0.616934  ]],

       [[0.94374808, 0.6818203 , 0.3595079 , 0.43703195],
        [0.6976312 , 0.06022547, 0.66676672, 0.67063787],
        [0.21038256, 0.1289263 , 0.31542835, 0.36371077]]])

In [45]:
r=np.random.randint(5,10,(2,3))
r

array([[9, 8, 9],
       [9, 9, 5]])

In [62]:
#shuffle로 데이터의 순서를 바꿀 수 있다. 다만 row내의 데이터만 shuffle!
np.random.shuffle(r)
r

array([[9, 9, 5],
       [9, 8, 9]])

In [63]:
print(list(range(5)))
print([0.1,0,0.3,0.6,0])
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0])

[0, 1, 2, 3, 4]
[0.1, 0, 0.3, 0.6, 0]


array([3, 0, 3, 0, 3, 3, 3, 3, 3, 0], dtype=int64)

In [64]:
r

array([[9, 9, 5],
       [9, 8, 9]])

In [66]:
#unique로 데이터의 유일한 값에 대한 리스트와 return_count=True를 통해 값의 개수를 알 수 있다.
index,count=np.unique(r,return_counts=True)
print(index)
print(count)

[5 8 9]
[1 1 4]


### stack
- 행렬을 쌓는 것과 같이 합치는 방법

In [67]:
na1=np.arange(6)
na2=np.arange(6,12)
na1=np.random.randint(10,size=(2,3))
na2=np.random.randint(10,size=(2,3))
print(na1,na1.shape)
print(na2,na2.shape)

[[2 7 2]
 [9 2 3]] (2, 3)
[[3 2 3]
 [4 1 2]] (2, 3)


In [69]:
na3=np.stack((na1,na2))
print(na3,na3.shape)
#그냥 stack은 두 함수를 stack한다. depth개념으로!! 진짜로 stack이다 생각해보니!!

[[[2 7 2]
  [9 2 3]]

 [[3 2 3]
  [4 1 2]]] (2, 2, 3)


In [71]:
na3=np.stack((na1,na2),axis=1)
print(na3,na3.shape)
#똑같이 depth늘리면서 stack하는데 row끼리 mapping하면서 stack한다!

[[[2 7 2]
  [3 2 3]]

 [[9 2 3]
  [4 1 2]]] (2, 2, 3)


In [73]:
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(range(7)[i:i+3])
ls

range(0, 7) 0 3
range(0, 3)
[0, 1, 2]

range(0, 7) 1 4
range(1, 4)
[1, 2, 3]

range(0, 7) 2 5
range(2, 5)
[2, 3, 4]

range(0, 7) 3 6
range(3, 6)
[3, 4, 5]

range(0, 7) 4 7
range(4, 7)
[4, 5, 6]



[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [76]:
#수직으로 합치기!
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [77]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))
#위의 stack는 다르지만 vertical하게 쌓아올린다. not perspective of depth!

array([[1, 2, 3],
       [2, 3, 4]])

In [78]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))
#이 소스코드를 보면 체계가 보인다.

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [75]:
#수평으로 합치기! 그냥 리스트가 된다!
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [81]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))
#row vector는 그대로 리스트로 붙여준다.(stack!)

array([1, 2, 3, 2, 3, 4])

In [82]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))
#이 소스코드를 보면 좀 보인다. a의 열벡터와 b의 열벡터가 horizontal하게 붙었다.

array([[1, 2],
       [2, 3],
       [3, 4]])

### concatenate(결합)
- 가로 결합은 열의 갯수가 같아야 한다.
- 세로 결합은 행의 갯수가 같아야 한다.

In [1]:
r1=np.random.randint(10,size=(2,3))
print(r1,r1.shape)

[[9 6 8]
 [4 8 1]] (2, 3)


In [3]:
r2=np.random.randint(10,size=(3,2))
print(r2,r2.shape)

[[1 6]
 [4 1]
 [4 7]] (3, 2)


In [5]:
r3=np.random.randint(10,size=(3,3))
print(r3,r3.shape)

[[7 1 1]
 [1 6 8]
 [2 6 4]] (3, 3)


In [6]:
#smiliar with vstack!!
np.concatenate([r1,r3])

array([[9, 6, 8],
       [4, 8, 1],
       [7, 1, 1],
       [1, 6, 8],
       [2, 6, 4]])

In [10]:
# smimilar with hstack!!
np.concatenate([r2,r3],axis=1)

array([[1, 6, 7, 1, 1],
       [4, 1, 1, 6, 8],
       [4, 7, 2, 6, 4]])

### Split

In [11]:
r=np.arange(0,10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
r1=np.split(r,[5])
r1

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [15]:
r1,r2,r3,r4,r5=np.split(r,[2,4,6,8])
r1,r2,r3,r4,r5

(array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]))

### vsplit/hsplit
- 행렬을 수직,수평으로 나눈다.

In [17]:
r=np.random.randint(10,size=(4,6))
r

array([[3, 7, 0, 7, 7, 0],
       [1, 4, 4, 0, 0, 3],
       [0, 7, 3, 6, 4, 8],
       [2, 1, 5, 9, 9, 3]])

In [19]:
#이게 왜 vertical split인지 의아할 수도 있지만, vertical부분(row쪽)에서 split했다고 
#생각하자!!
r1,r2=np.vsplit(r,[2])
print(r1)
print(r2)

[[3 7 0 7 7 0]
 [1 4 4 0 0 3]]
[[0 7 3 6 4 8]
 [2 1 5 9 9 3]]


In [20]:
r1,r2=np.hsplit(r,[3])
print(r1)
print(r2)

[[3 7 0]
 [1 4 4]
 [0 7 3]
 [2 1 5]]
[[7 7 0]
 [0 0 3]
 [6 4 8]
 [9 9 3]]


### sort

In [21]:
r1=np.random.randint(10,size=(3,3))
print(r1)

[[9 1 8]
 [2 1 5]
 [1 5 0]]


In [23]:
r1.sort()
r1
#그냥 sort를 하면 행단위로 그 안에 있는 요소들끼리만 sorting이 일어난다.

array([[1, 8, 9],
       [1, 2, 5],
       [0, 1, 5]])

In [25]:
r1.sort(axis=0)
r1
#axis=0을 통해 세로 sorting이 일어났다!

array([[0, 1, 5],
       [1, 2, 5],
       [1, 8, 9]])

- 1부터 9까지 무작위로 들어가는 3*3 행렬을 만들고 무작위로 섞어보자!

In [39]:
result=np.arange(1,10)
result=np.reshape(result,(3,3))
result
# result.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
np.random.shuffle(result)
result

array([[4, 1, 7],
       [5, 2, 8],
       [6, 3, 9]])

In [53]:
result=result.T
result

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [54]:
np.random.shuffle(result)
result

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])