## 행렬의 미분

In [1]:
import scipy as sp
import numpy as np

### Rosenburg 함수 Optimization
- (SGD) Steepest Gradient Descent Method

In [2]:
def f2(x):
    return (1 - x[0])**2 + 100.0 * (x[1] - x[0]**2)**2

In [3]:
def f2p(x):
    """gradient of f2(x)"""
    x1_val= 400*x[0]**3 -400*x[0]*x[1] + 2*x[0] -2
    x2_val= -200*x[0]**2 + 200*x[1]
    return np.array([x1_val,x2_val])

초기점 변경

In [4]:
a = (-3,-3)
result = sp.optimize.minimize(f2, a)
print(result)

      fun: 2.1206175523975426e-11
 hess_inv: array([[0.49908004, 0.99785144],
       [0.99785144, 2.00005392]])
      jac: array([ 6.74865667e-06, -3.49484575e-06])
  message: 'Optimization terminated successfully.'
     nfev: 316
      nit: 63
     njev: 79
   status: 0
  success: True
        x: array([0.9999954 , 0.99999078])


그레디언트 벡터 함수를 구현

In [5]:
a = (-2,2)
result = sp.optimize.minimize(f2, a, jac=f2p)
print(result)

      fun: 9.81729719189136e-14
 hess_inv: array([[0.48098005, 0.95985458],
       [0.95985458, 1.92027267]])
      jac: array([-8.75835558e-06,  4.59236327e-06])
  message: 'Optimization terminated successfully.'
     nfev: 42
      nit: 35
     njev: 42
   status: 0
  success: True
        x: array([1.00000021, 1.00000045])


### 2차 도함수를 사용한 방법
1차 도함수인 그레디언트 정보 뿐 아니라 2차 도함수인 헤시안 행렬 정보를 사용하여 계산하는 방법이 있다.
- CG(conjugated gradient)
- BFGS(Broyden-Fletcher-Goldfarb-Shanno)

In [6]:
a=(-2,2)
result=sp.optimize.minimize(f2,a,jac=f2p,method='CG')
print(result)

     fun: 6.177281807662137e-16
     jac: array([-7.45841833e-09, -2.11025224e-08])
 message: 'Optimization terminated successfully.'
    nfev: 79
     nit: 34
    njev: 79
  status: 0
 success: True
       x: array([0.99999998, 0.99999995])


In [7]:
a=(-2,2)
result=sp.optimize.minimize(f2,a,jac=f2p,method='BFGS')
print(result)

      fun: 9.81729719189136e-14
 hess_inv: array([[0.48098005, 0.95985458],
       [0.95985458, 1.92027267]])
      jac: array([-8.75835558e-06,  4.59236327e-06])
  message: 'Optimization terminated successfully.'
     nfev: 42
      nit: 35
     njev: 42
   status: 0
  success: True
        x: array([1.00000021, 1.00000045])


In [104]:
def f1logs(x):
    return -np.log(x[0]) - np.log(x[1])

def eq_constraint(x):
    return x[0] + x[1] - 1

sp.optimize.fmin_slsqp(f1logs, np.array([1, 1]), eqcons=[eq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 1.3862943611198901
            Iterations: 2
            Function evaluations: 8
            Gradient evaluations: 2


array([0.5, 0.5])

In [105]:
def f2(x):
    return np.sqrt((x[0] - 4) ** 2 + (x[1] - 2) ** 2)

def ieq_constraint(x):
    return np.atleast_1d(1 - np.sum(np.abs(x)))

sp.optimize.fmin_slsqp(f2, np.array([0, 0]), ieqcons=[ieq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 3.605551280732028
            Iterations: 11
            Function evaluations: 77
            Gradient evaluations: 11


array([9.99999981e-01, 1.89941792e-08])

In [8]:
def f2(x):
    return np.sqrt((x[0]-4)**2 + (x[1]-2)**2)

def ieq_constraint(x):
    return np.atleast_1d(1-np.sum(np.abs(x)))

In [10]:
sp.optimize.fmin_slsqp(f2,np.array([0,0]), ieqcons=[ieq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 3.605551280732028
            Iterations: 11
            Function evaluations: 77
            Gradient evaluations: 11


array([9.99999981e-01, 1.89941792e-08])

In [ ]:
def f2(x):
    return np.sqrt((x[0]-4)**2 + (x[1]-2)**2)

def ieq_constraint(x):
    return np.atleast_1d(1-np.sum(np.abs(x)))

In [28]:
ls=[]
for i in range(1,11):
    result=sp.optimize.fmin_slsqp(f2,np.array([0,0]), ieqcons=[lambda x: np.atleast_1d(i-np.sum(np.abs(x)))])
    ls.append(result)
ls

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 3.605551280732028
            Iterations: 11
            Function evaluations: 77
            Gradient evaluations: 11
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 2.8284287493322235
            Iterations: 8
            Function evaluations: 38
            Gradient evaluations: 8
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 2.1213203438762323
            Iterations: 6
            Function evaluations: 24
            Gradient evaluations: 6
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 1.4142135623742935
            Iterations: 5
            Function evaluations: 21
            Gradient evaluations: 5
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.7071067910728857
            Iterations: 5
            Function evalua

[array([9.99999981e-01, 1.89941792e-08]),
 array([1.9978564, 0.0021436]),
 array([2.4999741, 0.5000259]),
 array([2.9999986, 1.0000014]),
 array([3.49991639, 1.50008361]),
 array([4.00000057, 1.99999904]),
 array([3.99999982, 1.9999989 ]),
 array([4.00000041, 2.00000031]),
 array([3.99999992, 1.9999996 ]),
 array([3.99999992, 1.9999996 ])]

In [29]:
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
df=pd.DataFrame(ls,columns=['x','y'],index=[1,2,3,4,5,6,7,8,9,10])
df['slop']=df['y']/df['x']
df

x             y          slop
1   1.000000  1.899418e-08  1.899418e-08
2   1.997856  2.143601e-03  1.072950e-03
3   2.499974  5.000259e-01  2.000124e-01
4   2.999999  1.000001e+00  3.333340e-01
5   3.499916  1.500084e+00  4.286056e-01
6   4.000001  1.999999e+00  4.999997e-01
7   4.000000  1.999999e+00  4.999997e-01
8   4.000000  2.000000e+00  5.000000e-01
9   4.000000  2.000000e+00  4.999999e-01
10  4.000000  2.000000e+00  4.999999e-01