## Numpy practice:
- Numpy: Calculate
    - basic calculate
    - braodcasting
    - functions
    - performance

In [1]:
import numpy as np

In [3]:
ls=[1,2,3,4,5]
for idx in range(len(ls)):
    ls[idx]=ls[idx]*3
ls
# in list case

[3, 6, 9, 12, 15]

In [6]:
na=np.array([1,2,3,4,5])
print(na)
print(na*3)
# array case, much intuitive!

[1 2 3 4 5]
[ 3  6  9 12 15]


In [9]:
na1=np.array([1,2,3,4,5])
na2=np.array([2,3,4,5,6])
print(na1*na2)
# mapping the component muplication

[ 2  6 12 20 30]


In [10]:
na1==9,na2>5

(array([False, False, False, False, False]),
 array([False, False, False, False,  True]))

In [11]:
print(na2)
print(na2[idx])

[2 3 4 5 6]
6


In [14]:
na1=np.array([1,2,3,4,5])
na2=np.array([1,3,3,4,4])
print(na1==na2)
print(na1[na1==na2]) #extract the True value.

[ True False  True  True False]
[1 3 4]


In [16]:
na1=np.array([1,2,3,4,5])
na2=np.array([1,3,3,4,5])
print(np.all(na1==na2))#if there is no False value, then return the True
print(np.any(na1==na2))#if there is at least one True value, then return the True

False
True


### functions
- min,max,argmin,armax
- sum,mean,median,std,var
- all,any
- quartile
- exp,log

In [26]:
r=np.random.rand(2,3)
r_num=(r*10).astype('int64')
print("r_num:",r_num)
print("min: ",r_num.min())
print("max: ",r_num.max())
print("argmin: ",r_num.argmin())#the index of min value
print("argmax: ",r_num.argmax())#the index of max value
print("mean: ",r_num.mean())
print("sum: ",np.sum(r_num))
print("sum_axis_0: ",np.sum(r_num,axis=0))#sum culmulatively perspective of col
print("sum_axis_1: ",np.sum(r_num,axis=1))#sum culmulatively perspective of row
print("median: ",np.median(r_num))
print("std: ",np.std(r_num))
print("var: ",np.var(r_num))

r_num: [[1 2 8]
 [7 5 2]]
min:  1
max:  8
argmin:  0
argmax:  2
mean:  4.166666666666667
sum:  25
sum_axis_0:  [ 8  7 10]
sum_axis_1:  [11 14]
median:  3.5
std:  2.6718699236468995
var:  7.138888888888888


In [28]:
# quartile
na=np.array([num for num in range(0,100+1)])
print(na)
np.percentile(na,25),np.percentile(na,45)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


(25.0, 45.0)

In [31]:
#exponential function
na=np.arange(1,6)
print(na)
print(np.exp(na))#e**1,e**2,e**3,e**4,e**5

[1 2 3 4 5]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [33]:
# logarithm function
na=np.arange(1,6)
print(na)
print(np.log(na))
# in log function log10 is default, 
# log1,log2,log3,log4,log5 in default value.

[1 2 3 4 5]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [34]:
ls=[]
size=int(1E7)
for data in range(size):
    ls.append(data)
na=np.array(ls)

In [35]:
%%time
count=0
for idx in range(len(ls)):
    if (ls[idx]%3==0) or (ls[idx]%5==0):
        count+=1
print(count)

4666667
Wall time: 1.57 s


In [37]:
%%time
count=len(na[(na%3==0) | (na%5==0)])
print(count)
#list comprehension's speed is much faster! 
# And we should use performance &,| instead of and, or

4666667
Wall time: 141 ms


## correlation coefficient
- Pearson correltion coefficient
- Spearson correlation coefficient

In [44]:
data1=np.random.randint(10,size=20)
data1.sort()
data1

array([0, 0, 1, 2, 2, 2, 4, 4, 4, 5, 6, 7, 7, 7, 7, 8, 8, 9, 9, 9])

In [49]:
data2=np.random.randint(20,size=20)
data2.sort()
data2=data2[::-1]#reverse sorting
data2#it doesn't return so, we should allocate the variable

array([19, 15, 12, 11,  9,  8,  8,  8,  7,  7,  6,  6,  5,  4,  3,  2,  1,
        0,  0,  0])

In [54]:
print(data1)
print(data2)
print(np.corrcoef(data1,data2))
print(np.corrcoef(data1,data2)[0])
print(np.corrcoef(data1,data2)[0][1])

[0 0 1 2 2 2 4 4 4 5 6 7 7 7 7 8 8 9 9 9]
[19 15 12 11  9  8  8  8  7  7  6  6  5  4  3  2  1  0  0  0]
[[ 1.         -0.94651127]
 [-0.94651127  1.        ]]
[ 1.         -0.94651127]
-0.9465112701524614


In [85]:
na1=np.random.randint(1,20,size=(5,5))
na2=np.random.randint(1,20,size=(5,5))
print(na1)
print(na2)

[[ 8  8 18  1 18]
 [ 5  8 18  6  2]
 [13  4 19 16  6]
 [ 5  9  6 13  9]
 [ 4  9  2 15 15]]
[[15  3  8 19 19]
 [16 16  6 14 11]
 [ 4  7 15 17  2]
 [13  3  6 13 16]
 [18 19 15  2  8]]


In [86]:
correl=np.corrcoef(na1,na2)
print(correl)
print(correl.shape)

[[ 1.          0.3162961  -0.06788656 -0.54656215 -0.2933633  -0.14143091
  -0.7416202  -0.33721959 -0.02251506  0.25827275]
 [ 0.3162961   1.          0.6033713  -0.3482869  -0.69881035 -0.60281548
  -0.67424542  0.62059734 -0.68292996  0.31966626]
 [-0.06788656  0.6033713   1.         -0.12675121 -0.42497412  0.18997184
  -0.50528399  0.74060851  0.05282244 -0.23775869]
 [-0.54656215 -0.3482869  -0.12675121  1.          0.85919926  0.34264839
   0.2233567   0.4070295   0.18463724 -0.79286742]
 [-0.2933633  -0.69881035 -0.42497412  0.85919926  1.          0.56651766
   0.27462597 -0.06823485  0.50873329 -0.77246089]
 [-0.14143091 -0.60281548  0.18997184  0.34264839  0.56651766  1.
   0.03847122 -0.0740519   0.97247816 -0.76406281]
 [-0.7416202  -0.67424542 -0.50528399  0.2233567   0.27462597  0.03847122
   1.         -0.3641949   0.08046064  0.13765388]
 [-0.33721959  0.62059734  0.74060851  0.4070295  -0.06823485 -0.0740519
  -0.3641949   1.         -0.29569926 -0.40420694]
 [-0.0225